/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lmatei' at '3/24/16 4:08 PM' with Gradle 2.11
 *
 * @author lmatei, @date 3/24/16 4:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
